apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster.labels" . | nindent 4 }}
  {{- $annotations := (include "shield.annotations" .) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- include "cluster.secret" . | nindent 2 }}
