{{- if (include "host.rbac.role.create" .) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "host.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "host.rbac_labels" . | nindent 4 }}
  {{- $rbacAnnotations := (include "host.rbac_annotations" .) }}
  {{- if $rbacAnnotations }}
  annotations:
    {{- $rbacAnnotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "host.fullname" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "host.service_account_name" . }}
{{- end }}
