{{- if (include "host.rbac.service_account.create" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "host.service_account_name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "host.rbac_labels" . | nindent 4 }}
  {{- $rbacAnnotations := (include "host.rbac_annotations" .) }}
  {{- if $rbacAnnotations }}
  annotations:
    {{- $rbacAnnotations | nindent 4 }}
  {{- end }}
{{- end }}
