apiVersion: v2
appVersion: 0.12.1
description: Sysdig Registry Scanner
home: https://www.sysdig.com/
icon: https://avatars.githubusercontent.com/u/5068817?s=200&v=4
maintainers:
- name: sysdiglabs
name: registry-scanner
type: application
version: 1.11.1
