---
name: Update sysdig/sysdig-kubectl image reference for Helm tests

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  pull-requests: write

jobs:
  kubectl-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@2efa15cbae1751f532f9bfc88f56adafd6d1faed # v3.8.0

      - name: Run Updatecli
        run: "updatecli apply --config .github/updatecli.d/config-update-kubectl-image.yaml"
        env:
          GITHUB_TOKEN: "${{ secrets.TOOLS_JENKINS_ADMIN_ACCESS_GITHUB_TOKEN }}"
